spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: EmployeeProjectManagementDB
#  security:
#    user:
#      name: admin
#      password: admin
#      host: everEmpMongo
#      port: 27017

server:
  port: 8081